name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish

      - name: Create tag
        run: |
          version="$(jq -r '.version' deno.json)"
          git config user.name "GitHub Actions"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "${version}" -m "Release v${version}"
          git push origin --tags
